"""empty message

Revision ID: 0a8668feb933
Revises: 13e1ffe38d0f
Create Date: 2017-12-15 20:32:10.230341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8668feb933'
down_revision = '13e1ffe38d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
