"""empty message

Revision ID: 0bc4c20a60f3
Revises: 64497f739c48
Create Date: 2017-12-15 19:41:37.701357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc4c20a60f3'
down_revision = '64497f739c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_account_no', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['phoneNumber'])
    op.create_unique_constraint(None, 'customers', ['account_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('ix_customers_account_no', 'customers', ['account_no'], unique=True)
    # ### end Alembic commands ###
