"""empty message

Revision ID: 13e1ffe38d0f
Revises: 86256ba1d736
Create Date: 2017-12-15 20:30:42.065227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e1ffe38d0f'
down_revision = '86256ba1d736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_phoneNumber'), 'customers', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phoneNumber'), table_name='customers')
    # ### end Alembic commands ###
