"""empty message

Revision ID: 14d438e9e209
Revises: 0a8668feb933
Create Date: 2017-12-15 20:33:26.783587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d438e9e209'
down_revision = '0a8668feb933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_phoneNumber', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['phoneNumber'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('ix_customers_phoneNumber', 'customers', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###
