"""empty message

Revision ID: 44c929fba1bd
Revises: 6f296e3e74c0
Create Date: 2017-12-15 20:08:15.516761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c929fba1bd'
down_revision = '6f296e3e74c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_customers_phoneNumber'), 'customers', ['phoneNumber'], unique=True)
    # op.drop_index('ix_customers_phoneNumber', table_name='customers')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_customers_phoneNumber', 'customers', ['phoneNumber'], unique=True)
    # op.drop_index(op.f('ix_customers_phoneNumber'), table_name='customers')
    # ### end Alembic commands ###
    pass
