"""empty message

Revision ID: 557ca856e24e
Revises: c68395901337
Create Date: 2017-12-14 21:15:12.459883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557ca856e24e'
down_revision = 'c68395901337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('processed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'processed_on')
    # ### end Alembic commands ###
