"""empty message

Revision ID: 64497f739c48
Revises: d3962d8c38ad
Create Date: 2017-12-15 19:37:58.732492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64497f739c48'
down_revision = 'd3962d8c38ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_phoneNumber', table_name='customers')
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permisions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permisions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
