"""empty message

Revision ID: 6f296e3e74c0
Revises: 0bc4c20a60f3
Create Date: 2017-12-15 19:42:13.176678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f296e3e74c0'
down_revision = '0bc4c20a60f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_phoneNumber'), 'customers', ['phoneNumber'], unique=True)
    op.drop_constraint('customers_phoneNumber_key', 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customers_phoneNumber_key', 'customers', ['phoneNumber'])
    op.drop_index(op.f('ix_customers_phoneNumber'), table_name='customers')
    # ### end Alembic commands ###
