"""empty message

Revision ID: 77aa60b02400
Revises: 2a3c4ac74ab0
Create Date: 2017-12-11 20:11:03.343737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77aa60b02400'
down_revision = '2a3c4ac74ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('from_', sa.String(), nullable=True),
    sa.Column('to_', sa.String(), nullable=True),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_messages_text'), 'messages', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_text'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
