"""empty message

Revision ID: 86256ba1d736
Revises: 44c929fba1bd
Create Date: 2017-12-15 20:19:37.713402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86256ba1d736'
down_revision = '44c929fba1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_phoneNumber', table_name='customers')
    op.add_column('users', sa.Column('avatar_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    op.create_index('ix_customers_phoneNumber', 'customers', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###
